name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted, large ]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      # Add our SSH key into ssh agent to authenticate with our Cloud Container server
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Build Statamic site
        run: npm run build:prod

      - name: Clear artisan cache and cache route
        run: |
          php artisan cache:clear
          php artisan route:clear
          php artisan route:cache
          php please stache:refresh

      - name: Rsync files
        run: >
          rsync -avrc --delete --exclude-from=ci-exclude.txt
          -e 'ssh -o StrictHostKeyChecking=no'
          ./ "${{ vars.PROD_SSH_USER }}"@${{ vars.PROD_SERVER }}:"${{ vars.DEPLOY_PATH }}"

      - name: Warn the cache
        run: >
          ssh -o StrictHostKeyChecking=no "${{ vars.PROD_SSH_USER }}"@${{ vars.PROD_SERVER }}
          "cd /container/application &&
          sed -i "s/CACHE_TIMESTAMP=.*/CACHE_TIMESTAMP=${{ github.sha }}/g" .env &&
          php please static:warm"
